FROM centos:7

WORKDIR /
RUN wget https://desktop.githubusercontent.com/releases/2.5.7-cfea2832/GitHubDesktopSetup.exe
RUN wget https://desktop.githubusercontent.com/releases/2.5.7-cfea2832/GitHubDesktop.zip
